---
- name: Install and configure Laravel app on Ubuntu
  hosts: laravel_servers
  become: yes
  vars:
    php_version: "7.4"
    project_name: "projectname"
    server_ip: "192.168.56.76"
    doc_root: "/var/www/html/{{ project_name }}"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Install PHP and required extensions
      apt:
        name:
          - "php{{ php_version }}"
          - "libapache2-mod-php{{ php_version }}"
          - "php{{ php_version }}-curl"
          - "php-pear"
          - "php{{ php_version }}-gd"
          - "php{{ php_version }}-dev"
          - "php{{ php_version }}-zip"
          - "php{{ php_version }}-mbstring"
          - "php{{ php_version }}-mysql"
          - "php{{ php_version }}-xml"
          - curl
          - unzip
        state: present

    - name: Download Composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php

    - name: Install Composer globally
      command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer

    - name: Create Laravel project
      command: composer create-project laravel/laravel {{ project_name }} --prefer-dist --no-interaction --optimize-autoloader
      args:
        chdir: /var/www/html
        creates: "{{ doc_root }}/artisan"
      environment:
        COMPOSER_ALLOW_SUPERUSER: "1"

    - name: Set permissions for project
      file:
        path: "{{ doc_root }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Set permissions for storage directory
      file:
        path: "{{ doc_root }}/storage"
        mode: '0775'
        recurse: yes

    - name: Create Apache virtual host for Laravel
      copy:
        dest: /etc/apache2/sites-available/laravel.conf
        content: |
          <VirtualHost *:80>
              ServerName {{ server_ip }}
              ServerAdmin admin@example.com
              DocumentRoot {{ doc_root }}/public

              <Directory {{ doc_root }}>
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

    - name: Enable Laravel site
      command: a2ensite laravel.conf
      args:
        creates: /etc/apache2/sites-enabled/laravel.conf

    - name: Enable Apache rewrite module
      command: a2enmod rewrite
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
