---
- name: Install and configure Laravel app on Ubuntu
  hosts: laravel_servers
  become: yes
  vars:
    php_version: "7.4"
    project_name: "projectname"
    server_ip: "192.168.56.84"
    doc_root: "/var/www/html/{{ project_name }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache, PHP and required extensions
      apt:
        name:
          - apache2
          - "php{{ php_version }}"
          - "libapache2-mod-php{{ php_version }}"
          - "php{{ php_version }}-curl"
          - "php{{ php_version }}-gd"
          - "php{{ php_version }}-dev"
          - "php{{ php_version }}-zip"
          - "php{{ php_version }}-mbstring"
          - "php{{ php_version }}-mysql"
          - "php{{ php_version }}-xml"
          - php-pear
          - curl
          - unzip
        state: present

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    # ----------------------------
    # Composer installation (with signature verification)
    # ----------------------------
    - name: Get Composer installer signature
      uri:
        url: https://composer.github.io/installer.sig
        return_content: yes
      register: composer_sig

    - name: Download Composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php

    - name: Verify Composer installer
      shell: |
        php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '{{ composer_sig.content | trim }}') { exit(0); } else { echo 'Invalid installer'; exit(1); }"
      args:
        warn: false

    - name: Install Composer globally
      command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer

    # ----------------------------
    # Laravel Installation
    # ----------------------------
    - name: Ensure /var/www/html owned by www-data
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes

    - name: Create Laravel project
      command: composer create-project laravel/laravel {{ project_name }} --prefer-dist --no-interaction
      args:
        chdir: /var/www/html
        creates: "{{ doc_root }}/artisan"

    - name: Set ownership for project files
      file:
        path: "{{ doc_root }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Set permissions for storage
      file:
        path: "{{ doc_root }}/storage"
        mode: '0775'
        recurse: yes

    - name: Set permissions for bootstrap/cache
      file:
        path: "{{ doc_root }}/bootstrap/cache"
        mode: '0775'
        recurse: yes

    # ----------------------------
    # Laravel Environment File
    # ----------------------------
    - name: Copy Laravel .env file
      copy:
        dest: "{{ doc_root }}/.env"
        content: |
          APP_NAME=Laravel
          APP_ENV=local
          APP_KEY=
          APP_DEBUG=true
          APP_URL=http://{{ server_ip }}

          LOG_CHANNEL=stack
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=debug

          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=laravel
          DB_USERNAME=laravel
          DB_PASSWORD=secret
        owner: www-data
        group: www-data
        mode: '0644'

    # ----------------------------
    # Apache Configuration
    # ----------------------------
    - name: Deploy Apache vhost for Laravel
      template:
        src: laravel.conf.j2
        dest: /etc/apache2/sites-available/laravel.conf
      notify: Restart Apache

    - name: Enable Laravel site
      apache2_site:
        state: enabled
        name: laravel.conf
      notify: Restart Apache

    - name: Enable Apache rewrite module
      apache2_module:
        name: rewrite
        state: present
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
